### PR TITLE
Added Turkish language support

### PR DESCRIPTION
**Pull request by bywkgexmkiltxh**

### CODE REVIEW

**Comment by yaira2** [comment]
@bywkgexmkiltxh do you have the Multilingual App Toolkit extension for Visual Studio? It's required to generate the resw file contents.

**Comment by bywkgexmkiltxh** [comment]
> @bywkgexmkiltxh do you have the Multilingual App Toolkit extension for Visual Studio? It's required to generate the resw file contents.

I'm sorry, I uninstalled Visual Studio after translating Quick-Pad, but I used Multilingual App Toolkit to translate the app. I'm not a developer, I translate apps using loco. If Multilingual App Toolkit is required now, I can download it again.

**Comment by yaira2** [comment]
It requires compiling the project with the extension installed. I tried from my side, but unfortunately, it doesn't look like the extensions is compatible on ARM64 devices.

**Comment by bywkgexmkiltxh** [comment]
> It requires compiling the project with the extension installed. I tried from my side, but unfortunately, it doesn't look like the extensions is compatible on ARM64 devices.

image
What does it mean?

**Comment by yaira2** [comment]
@bywkgexmkiltxh next to `Local Machine` in the toolbar, there is a dropdown menu to choose the build architecture. Try changing it to `x64`.

**Comment by bywkgexmkiltxh** [comment]
> @bywkgexmkiltxh next to `Local Machine` in the toolbar, there is a dropdown menu to choose the build architecture. Try changing it to `x64`.

[errors.log](https://github.com/user-attachments/files/16404183/errors.log)

**Comment by yaira2** [comment]
You might need to clean the solution and rebuild.
image

**Comment by bywkgexmkiltxh** [comment]
> You might need to clean the solution and rebuild. image

[errors2.log](https://github.com/user-attachments/files/16404572/errors2.log)

**Comment by yaira2** [comment]
Can you send a screenshot?

**Comment by bywkgexmkiltxh** [comment]
> Can you send a screenshot?

https://1drv.ms/v/c/349da573b3eea4cb/EaDnyWHIKnNKlh-pNqeojjEB6IIFC3dIAp0-RnUzIDiHPw?e=ru6AMt
Here is a screen recording

**Comment by yaira2** [comment]
Oh, I think you need to set the startup project.
- Right click `QuickPad.UI` in Solution Explorer
- Click "Set as startup project"

**Comment by bywkgexmkiltxh** [comment]
> Oh, I think you need to set the startup project.
> 
> * Right click `QuickPad.UI` in Solution Explorer
> * Click "Set as startup project"

[errors3.log](https://github.com/user-attachments/files/16405055/errors3.log)

We could give up at this point...

**Comment by yaira2** [comment]
> We could give up at this point...

I don't give up so easily...

Can you send a screenshot of Visual Studio? (no need for a full screen recording..)

**Comment by bywkgexmkiltxh** [comment]
> > We could give up at this point...
> 
> I don't give up so easily...
> 
> Can you send a screenshot of Visual Studio? (no need for a full screen recording..)

image

**Comment by yaira2** [comment]
Something in the project has been modified on your local device. Notice how your screenshot shows `.NET for Windows Universal`, the correct config is `Universal Windows`. I suggest reverting any local changes or recloning the repo.
image

**Comment by bywkgexmkiltxh** [comment]
> Something in the project has been modified on your local device. Notice how your screenshot shows `.NET for Windows Universal`, whereas the correct config should be `Universal Windows`. I suggest reverting any local changes or recloning the repo. image

I have already tried recloning the repo several times. During VS installation, I only checked "**Windows application development**
Build applications for the Windows Platform using WinUI with C# or optionally C++."
Is it the only option should be checked in the Visual Studio Installer software?

**Comment by yaira2** [comment]
You'll need to the UWP workflow.

**Comment by bywkgexmkiltxh** [comment]
> You'll need the UWP workflow.

Thank you, I successfully built the .msix installer but the package needs to be signed first. I created my own certificate and signed the app to run it on my computer.
image
Additionally, why do I have to select Turkish when the app is run for the first time? Isn't it supposed to detect my computer's set language and automatically switch to it?

**Comment by yaira2** [comment]
After compiling the project, was the resw file generated? If it was, you can commit the changes to this PR for final review.

**Comment by bywkgexmkiltxh** [comment]
> After compiling the project, was the resw file generated? If it was, you can commit the changes to this PR for final review.

Done

**Review by yaira2 — APPROVED** [review]
LGTM

**Comment by yaira2** [comment]
> Additionally, why do I have to select Turkish when the app is run for the first time? Isn't it supposed to detect my computer's set language and automatically switch to it?

Auto detection isn't currently supported in Quick Pad.

**Pull request merged**
